/**
 * @file adapter.ts
 * @module @callydus/email-wallet-adapter-openfort
 *
 * Full implementation of `EmailWalletAdapter` using the Openfort SDK v0.9.x.
 *
 * ## SDK version note
 *
 * This adapter targets `@openfort/openfort-js@^0.9.0`. The API changed significantly
 * between minor versions. If you upgrade the SDK, verify that the methods used here
 * still exist.
 *
 * ## Authentication model
 *
 * The Openfort SDK v0.9.x uses email+password authentication. The OTP flow expected
 * by `EmailWalletAdapter` is implemented by treating the `otp` parameter as a
 * temporary password. In a production integration, `requestOtp` would call your
 * own backend which generates a secure one-time password, sends it by email via
 * SES/SendGrid, and `signIn` verifies it before calling Openfort.
 *
 * For the direct Openfort integration pattern, we use `logInWithEmailPassword` where:
 * - The email serves as the username
 * - The OTP serves as a session-scoped password (generated by your backend)
 *
 * ## Embedded Wallet states
 *
 * Openfort v0.9.x `EmbeddedState` is a numeric enum:
 * - `0 = NONE`: SDK not initialized
 * - `1 = UNAUTHENTICATED`: Not signed in
 * - `2 = EMBEDDED_SIGNER_NOT_CONFIGURED`: Signed in, wallet not yet created
 * - `3 = CREATING_ACCOUNT`: Wallet creation in progress
 * - `4 = READY`: Signed in and wallet is available
 *
 * ## Transaction signing for Solana
 *
 * Solana uses Ed25519 with **raw bytes** — no keccak256 hashing.
 * Pass `hashMessage: false` to `embeddedWallet.signMessage()`.
 *
 * Flow:
 * 1. Serialize: `tx.serializeMessage()` (legacy) or `tx.message.serialize()` (versioned)
 * 2. Sign: `openfort.embeddedWallet.signMessage(bytes, { hashMessage: false })`
 * 3. Decode: `bs58.decode(signatureBase58)` → `Uint8Array`
 * 4. Attach: `tx.addSignature(publicKey, Buffer.from(signatureBytes))`
 */

import {
  AuthenticationError,
  ConfigurationError,
  SigningError,
  WalletNotFoundError,
} from '@callydus/email-wallet-core';
import type { EmailWalletAdapter, WalletAccount } from '@callydus/email-wallet-core';
import {
  AccountTypeEnum,
  ChainTypeEnum,
  EmbeddedState,
  Openfort,
  OpenfortConfiguration,
  RecoveryMethod,
  ShieldConfiguration,
} from '@openfort/openfort-js';
import { PublicKey, Transaction, type VersionedTransaction } from '@solana/web3.js';
import bs58 from 'bs58';
import { type OpenfortAdapterConfig, openfortAdapterConfigSchema } from './config.js';

/**
 * Implements `EmailWalletAdapter` using the Openfort SDK.
 *
 * Provides email-based Solana wallet creation, authentication, and signing
 * via the Openfort embedded wallet infrastructure.
 *
 * ## Authentication pattern
 *
 * The Openfort SDK v0.9.x uses email+password auth. The adapter maps the
 * `EmailWalletAdapter` OTP interface as follows:
 * - `requestOtp(email)`: No-op placeholder — in production, this triggers your
 *   backend to generate and email a one-time password.
 * - `signIn(email, otp)`: Calls `auth.logInWithEmailPassword` where `otp` is
 *   the one-time password generated by your backend.
 *
 * For a complete email OTP integration, pair this adapter with a backend
 * service that generates OTP codes and delivers them via email.
 *
 * ## Usage
 *
 * ```ts
 * const adapter = new OpenfortAdapter({
 *   publishableKey: process.env.OPENFORT_PUBLISHABLE_KEY!,
 *   shieldPublishableKey: process.env.OPENFORT_SHIELD_KEY!,
 * });
 * ```
 */
export class OpenfortAdapter implements EmailWalletAdapter {
  /**
   * The Openfort SDK instance.
   *
   * Initialized once in the constructor using `OpenfortConfiguration` and
   * `ShieldConfiguration` class instances (required by SDK v0.9+).
   *
   * @internal
   */
  private readonly openfort: Openfort;

  /**
   * Creates a new `OpenfortAdapter`.
   *
   * Validates the configuration using Zod and initializes the Openfort SDK.
   * Throws `ConfigurationError` immediately on invalid config.
   *
   * @param config - Openfort publishable key and Shield publishable key.
   * @throws {ConfigurationError} If the config fails validation.
   */
  constructor(config: OpenfortAdapterConfig) {
    const parsed = openfortAdapterConfigSchema.safeParse(config);
    if (!parsed.success) {
      throw new ConfigurationError(
        `Invalid OpenfortAdapter configuration: ${parsed.error.message}`,
        parsed.error,
      );
    }

    // SDK v0.9.x requires class instances, not plain objects.
    // OpenfortConfiguration wraps the publishableKey.
    // ShieldConfiguration wraps the shieldPublishableKey.
    this.openfort = new Openfort({
      baseConfiguration: new OpenfortConfiguration({
        publishableKey: parsed.data.publishableKey,
      }),
      shieldConfiguration: new ShieldConfiguration({
        shieldPublishableKey: parsed.data.shieldPublishableKey,
      }),
    });
  }

  // ─── OTP Flow ─────────────────────────────────────────────────────────────

  /**
   * Step 1: Prepares the system for OTP sign-in.
   *
   * ## Implementation note (Openfort SDK v0.9.x)
   *
   * The Openfort SDK v0.9.x uses email+password auth, not email OTP natively.
   * This method serves as a placeholder for the OTP delivery step. In production:
   * 1. Your backend generates a secure one-time password
   * 2. Your backend delivers it to the user via email (SES, SendGrid, etc.)
   * 3. The user enters the code in your UI
   * 4. `signIn(email, otp)` authenticates with Openfort using that code as password
   *
   * This method does not call Openfort directly — it validates the email format
   * and returns. If you want to also sign up new users, call `auth.signUpWithEmailPassword`
   * in a backend service.
   *
   * @param email - The email address to validate.
   * @throws {AuthenticationError} If the email format is invalid.
   */
  async requestOtp(email: string): Promise<void> {
    // Basic email format validation before attempting auth
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      throw new AuthenticationError(`Invalid email address: ${email}`);
    }
    // In production: call your backend here to generate and send the OTP.
    // The OTP will be passed as the `otp` parameter to `signIn()`.
  }

  /**
   * Step 2: Authenticates with Openfort and creates/recovers the Solana wallet.
   *
   * ## Authentication
   *
   * Calls `auth.logInWithEmailPassword` where the `otp` parameter is used as
   * the password. This requires the user to have an Openfort account with that
   * email (created via `auth.signUpWithEmailPassword` on first use).
   *
   * ## Wallet lifecycle
   *
   * After authentication:
   * - `EmbeddedState.EMBEDDED_SIGNER_NOT_CONFIGURED` (2): First sign-in — creates the wallet
   * - `EmbeddedState.READY` (4): Subsequent sign-in — wallet already exists
   *
   * @param email - The user's email address.
   * @param otp   - The one-time password (or regular password for testing).
   * @returns The authenticated `WalletAccount`.
   * @throws {AuthenticationError} If authentication fails.
   * @throws {WalletNotFoundError} If wallet cannot be created or retrieved.
   */
  async signIn(email: string, otp: string): Promise<WalletAccount> {
    try {
      await this.openfort.auth.logInWithEmailPassword({ email, password: otp });
    } catch (err) {
      throw new AuthenticationError(
        `Authentication failed for ${email}: ${errorMessage(err)}`,
        err,
      );
    }

    // After successful auth, check the embedded wallet state.
    try {
      const state = await this.openfort.embeddedWallet.getEmbeddedState();

      if (state === EmbeddedState.EMBEDDED_SIGNER_NOT_CONFIGURED) {
        // First sign-in: create the Solana EOA wallet.
        // EOA (Externally Owned Account) = standard keypair for Solana.
        // SVM (Solana Virtual Machine) = tells Openfort to use Ed25519.
        // RecoveryMethod.AUTOMATIC = Openfort Shield manages recovery automatically.
        await this.openfort.embeddedWallet.create({
          accountType: AccountTypeEnum.EOA,
          chainType: ChainTypeEnum.SVM,
          recoveryParams: {
            recoveryMethod: RecoveryMethod.AUTOMATIC,
          },
        });
      } else if (state === EmbeddedState.READY) {
        // Wallet already exists — no action needed.
      } else if (state === EmbeddedState.CREATING_ACCOUNT) {
        // Wallet creation is in progress (race condition) — wait briefly.
        // In production, poll until state reaches READY.
        await waitForReady(this.openfort);
      } else {
        throw new WalletNotFoundError(
          `Unexpected embedded wallet state after authentication: ${state}`,
        );
      }
    } catch (err) {
      if (err instanceof WalletNotFoundError) throw err;
      throw new WalletNotFoundError(
        `Failed to initialize embedded wallet: ${errorMessage(err)}`,
        err,
      );
    }

    return this.fetchWalletAccount(email);
  }

  /**
   * Signs out the current user.
   *
   * @throws {AuthenticationError} If the sign-out request fails.
   */
  async signOut(): Promise<void> {
    try {
      await this.openfort.auth.logout();
    } catch (err) {
      throw new AuthenticationError(`Sign-out failed: ${errorMessage(err)}`, err);
    }
  }

  // ─── Transaction signing ──────────────────────────────────────────────────

  /**
   * Signs a Solana transaction with the embedded wallet.
   *
   * **Critical**: `hashMessage: false` must be passed to disable keccak256 hashing.
   * Solana uses raw Ed25519 signing — no hash transformation.
   *
   * @param tx - The transaction to sign.
   * @returns The signed transaction.
   * @throws {SigningError} If signing fails.
   * @throws {WalletNotFoundError} If not authenticated.
   */
  async signTransaction<T extends Transaction | VersionedTransaction>(tx: T): Promise<T> {
    await this.assertReady();

    try {
      if (tx instanceof Transaction) {
        return (await this.signLegacyTransaction(tx)) as T;
      }
      return (await this.signVersionedTransaction(tx as VersionedTransaction)) as T;
    } catch (err) {
      if (err instanceof SigningError || err instanceof WalletNotFoundError) throw err;
      throw new SigningError(`Transaction signing failed: ${errorMessage(err)}`, err);
    }
  }

  /**
   * Signs multiple Solana transactions in a batch.
   *
   * @param txs - The transactions to sign.
   * @returns All transactions with signatures attached.
   * @throws {SigningError} If any signing fails.
   * @throws {WalletNotFoundError} If not authenticated.
   */
  async signAllTransactions<T extends Transaction | VersionedTransaction>(txs: T[]): Promise<T[]> {
    const signed: T[] = [];
    for (const tx of txs) {
      signed.push(await this.signTransaction(tx));
    }
    return signed;
  }

  // ─── Wallet info ──────────────────────────────────────────────────────────

  /**
   * Returns the Solana public key of the authenticated wallet.
   *
   * Calls `embeddedWallet.get()` which returns an `EmbeddedAccount` with
   * the wallet's `address` (Base58 string). We convert it to a `PublicKey`.
   *
   * @returns The wallet's `PublicKey`.
   * @throws {WalletNotFoundError} If not authenticated or wallet not created.
   */
  async getAddress(): Promise<PublicKey> {
    try {
      const account = await this.openfort.embeddedWallet.get();
      if (!account?.address) {
        throw new WalletNotFoundError('Openfort returned no wallet address.');
      }
      return new PublicKey(account.address);
    } catch (err) {
      if (err instanceof WalletNotFoundError) throw err;
      throw new WalletNotFoundError(`Could not retrieve wallet address: ${errorMessage(err)}`, err);
    }
  }

  /**
   * Checks whether the wallet is in the `READY` state.
   *
   * `EmbeddedState.READY === 4` in SDK v0.9.x.
   * Never throws — returns `false` on any error.
   *
   * @returns `true` if authenticated and wallet is ready.
   */
  async isAuthenticated(): Promise<boolean> {
    try {
      const state = await this.openfort.embeddedWallet.getEmbeddedState();
      return state === EmbeddedState.READY;
    } catch {
      return false;
    }
  }

  // ─── Key export ───────────────────────────────────────────────────────────

  /**
   * Exports the raw private key of the embedded wallet.
   *
   * **SECURITY WARNING**: After export, the user is solely responsible for
   * securing the key. This cannot be undone.
   *
   * @returns Base58-encoded private key string.
   * @throws {WalletNotFoundError} If not authenticated.
   * @throws {SigningError} If the export request fails.
   */
  async exportPrivateKey(): Promise<string> {
    await this.assertReady();
    try {
      return await this.openfort.embeddedWallet.exportPrivateKey();
    } catch (err) {
      throw new SigningError(`Failed to export private key: ${errorMessage(err)}`, err);
    }
  }

  // ─── Private helpers ──────────────────────────────────────────────────────

  /**
   * Asserts that the wallet is in `READY` state.
   *
   * @throws {WalletNotFoundError} If the wallet is not ready.
   */
  private async assertReady(): Promise<void> {
    const authenticated = await this.isAuthenticated();
    if (!authenticated) {
      throw new WalletNotFoundError(
        'The embedded wallet is not ready. Authenticate first with requestOtp() and signIn().',
      );
    }
  }

  /**
   * Fetches the `WalletAccount` for the authenticated user.
   *
   * @param email - The authenticated user's email.
   * @returns `WalletAccount` with `address` and `email`.
   */
  private async fetchWalletAccount(email: string): Promise<WalletAccount> {
    try {
      const account = await this.openfort.embeddedWallet.get();
      if (!account?.address) {
        throw new WalletNotFoundError(
          'Wallet was created but address could not be retrieved. Please try again.',
        );
      }
      return {
        address: new PublicKey(account.address),
        email,
      };
    } catch (err) {
      if (err instanceof WalletNotFoundError) throw err;
      throw new WalletNotFoundError(
        `Failed to retrieve wallet after authentication: ${errorMessage(err)}`,
        err,
      );
    }
  }

  /**
   * Signs a legacy (non-versioned) Solana `Transaction`.
   *
   * Serializes with `tx.serializeMessage()` and signs the raw bytes
   * with `hashMessage: false` (critical for Solana).
   *
   * @param tx - The legacy transaction.
   * @returns The signed transaction.
   */
  private async signLegacyTransaction(tx: Transaction): Promise<Transaction> {
    let messageBytes: Uint8Array;
    try {
      messageBytes = tx.serializeMessage();
    } catch (err) {
      throw new SigningError(`Failed to serialize transaction message: ${errorMessage(err)}`, err);
    }

    // hashMessage: false is critical — Solana signs raw bytes, not keccak256(bytes)
    const signatureBase58 = await this.openfort.embeddedWallet.signMessage(messageBytes, {
      hashMessage: false,
    });

    const signatureBytes = bs58.decode(signatureBase58);
    const address = await this.getAddress();
    tx.addSignature(address, Buffer.from(signatureBytes));

    return tx;
  }

  /**
   * Signs a versioned (`VersionedTransaction`) Solana transaction.
   *
   * Uses `tx.message.serialize()` (not `serializeMessage()` which is for legacy).
   * Attaches the signature at index 0 (the fee payer position).
   *
   * @param tx - The versioned transaction.
   * @returns The signed versioned transaction.
   */
  private async signVersionedTransaction(tx: VersionedTransaction): Promise<VersionedTransaction> {
    let messageBytes: Uint8Array;
    try {
      messageBytes = tx.message.serialize();
    } catch (err) {
      throw new SigningError(
        `Failed to serialize versioned transaction message: ${errorMessage(err)}`,
        err,
      );
    }

    const signatureBase58 = await this.openfort.embeddedWallet.signMessage(messageBytes, {
      hashMessage: false,
    });

    const signatureBytes = bs58.decode(signatureBase58);
    // Get the wallet address to attach the signature to the correct signer slot
    const address = await this.getAddress();
    tx.addSignature(address, signatureBytes);

    return tx;
  }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/**
 * Polls the embedded wallet state until it reaches `READY`.
 *
 * Used when the state is `CREATING_ACCOUNT` (wallet creation in progress).
 * Polls every 500ms with a maximum of 20 attempts (10 seconds total).
 *
 * @param openfort - The Openfort SDK instance.
 * @throws {WalletNotFoundError} If the wallet doesn't become ready in time.
 *
 * @internal
 */
async function waitForReady(openfort: Openfort): Promise<void> {
  const MAX_ATTEMPTS = 20;
  const POLL_INTERVAL_MS = 500;

  for (let i = 0; i < MAX_ATTEMPTS; i++) {
    const state = await openfort.embeddedWallet.getEmbeddedState();
    if (state === EmbeddedState.READY) return;
    await new Promise<void>((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
  }

  throw new WalletNotFoundError('Wallet creation timed out. Please try signing in again.');
}

/**
 * Extracts a human-readable message from an unknown caught value.
 *
 * @param err - The caught value.
 * @returns A string representation.
 *
 * @internal
 */
function errorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  return String(err);
}
